apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: grafanadatasource-sample-cw
spec:
  instanceSelector:
    matchLabels:
      dashboards: "external-grafana"
  datasource:
    name: cloud-watch
    type: cloudwatch
    access: server
    isDefault: false
    jsonData:
      'tlsSkipVerify': false
      'timeInterval': "5s"
      "sigV4Auth": true,
      "sigV4AuthType": "ec2_iam_role"
      # "sigV4Region": {{ (lookup "v1" "ConfigMap" "argocd" "cluster-vars").data.AMG_AWS_REGION | default "no_value_yet" }}
      "sigV4Region": AMG_AWS_REGION
      "customMetricsNamespaces": "ContainerInsights/Prometheus"
      # "defaultRegion": {{ (lookup "v1" "ConfigMap" "argocd" "cluster-vars").data.AMG_AWS_REGION | default "no_value_yet" }}
      "defaultRegion": AMG_AWS_REGION
      "provisionedBy": "aws-datasource-provisioner-app"
    editable: true